name: main_v3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - spacy
  - spacy-model-en_core_web_sm
  - tensorflow=1.13.1
  - pip:
    - wandb==0.12.11
    - demographer==1.0.4
    - hydra-core
    - pandas==1.3.5
    - numpy
    - protobuf==3.12.0
    - scikit-learn
    - nltk
    - gensim
    - openpyxl
    - lxml
    - transformers
    - torch
    - spacytextblob