name: main
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - mlflow=1.24.0
  - pandas=1.3.5
  - numpy
  - scikit-learn
  - nltk
  - gensim
  - openpyxl
  - lxml
  - pip
  - tensorflow=1.13.1
  - pip:
    - wandb
    - demographer==1.0.4
    - hydra-core
    - protobuf==3.12.0