name: main
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - wandb
    - demographer==1.0.4
    - hydra-core
    - protobuf==3.12.0
    - mlflow==1.24.0
    - pandas==1.3.5
    - numpy
    - scikit-learn
    - nltk
    - gensim
    - openpyxl
    - lxml
    - tensorflow==1.13.1
    - ./components/component_utils