mode: local
main:
  project_name: metoo_research
  experiment_name: dev
  steps: all
components:
  consolidate_data:
    input_path: ./data/metoo_data.zip
    output: consolidated_data.csv
    samp_size: -1

  preprocess_data:
    input_path: components/artifacts/consolidated_data.csv
    output: preprocess_data.csv
    exclude: metoo,rt

  # infer_news:
  #   input_path: components/artifacts/preprocess_data.csv
  #   train_size: 0.75
  #   random_state: 0
  #   vocab_size: 10000

  train_lda:
    input_path: components/artifacts/preprocess_data.csv  
    train_size: 0.75
    random_state: 0
    vocab_size: 50000
    no_below: 10
    grid_search: False

  append_topics:
    model_path: components/artifacts/lda_model_num_topics=10-alpha=0.01-eta=0.21000000000000002
    dict_path: components/artifacts/dictionary
    data_path: components/artifacts/preprocess_data.csv
    output: append_topics.csv

  infer_demographics:
    input_path: components/artifacts/preprocess_data.csv
    output: inferred_demographics.csv

  postprocess_data:
    input_path: components/artifacts/append_topics.csv
    brand_path: ./data/brandfulllist.xlsx
    comp_path: ./data/companyfulllist.xlsx
    demo_path: components/artifacts/inferred_demographics.csv
    output: postprocess_data.csv
    influencer_thresh: 20000