name: preprocess_data
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow
  - pandas
  - gensim
  - numpy
  - pip
  - python=3.9
  - scikit-learn
  - pip:
    - wandb
    - ../component_utils