name: infer_account_types
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow
  - pandas
  - pyspark
  - pip
  - python=3.9
  - pip:
    - wandb
    - scikit-learn
    - ../component_utils