name: process_data
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow
  - pandas
  - pip
  - python
  - tensorflow=1.13.1
  - pip:
    - wandb
    - demographer==1.0.4
    - ../component_utils